### ISSUE TITLE
Naming Conventions Issue

### ISSUE THREAD

**Issue by juliannastepha** [juliannastepha/different-crops-same-image#1]
@charlie-quinn
I used the exact names I was told to use on the lesson page, yet for some reason markbot is saying that they do not follow the naming conventions. What should I do?
<img width="520" alt="Screen Shot 2019-10-29 at 12 40 40 PM" src="https://user-images.githubusercontent.com/43150245/67789023-ae93f700-fa49-11e9-8553-08a93fb1934d.png">

**Comment by charlie-quinn** [comment]
@thomasjbradley

Markbot will decide this assignment fails if:
  - image names follow proper naming conventions (removing or replacing the `@` glyph)
  - images are named correctly according to what Markbot is looking for

🤔

**Comment by thomasjbradley** [comment]
@juliannastepha What version of Markbot are you using? It needs to be at least `8.2.0` to support the `@2x` syntax.
